### PR TITLE
XChatsFilter: Fix separate group not in correct order list

### LINKED ISSUE #42: Separate Groups
The setting for "separate groups" is not being retained. It keeps disappearing and I have to kill and restart the app ever so often to get it back. I'm using the Beta.

### PR DESCRIPTION
**Pull request by BryanGIG**
Doing `set` in the same field repeatedly is useless, it doesn't set the list again after second time because it is already the same instance object as the previous object `tab`. 
The solution is to clear and create the list again.

Close #42

### CODE REVIEW

**Comment by ItsMadruga** [comment]
the error is still present

**Comment by BryanGIG** [comment]
> the error is still present

How'd you reproduce the bug? 
It seems to have fixed the issue for me when I press the back button.

**Comment by BryanGIG** [comment]
Before:
```
[ 2024-04-12T04:07:12.678    10190: 14840: 14840 I/LSPosed-Bridge  ] [Chats Filter] Tabs: [200, 800, 300, 600, 400]
.... Back button press ....
[ 2024-04-12T04:07:19.293    10190: 14840: 14840 I/LSPosed-Bridge  ] [Chats Filter] Tabs: [200, 300, 600, 800]
```

After:
```
[ 2024-04-12T04:09:56.565    10190: 16585: 16585 I/LSPosed-Bridge  ] [Chats Filter] Tabs: [200, 800, 300, 600, 400]
.... Back button press ....
[ 2024-04-12T04:09:59.754    10190: 16585: 16585 I/LSPosed-Bridge  ] [Chats Filter] Tabs: [200, 800, 300, 600, 400]
```

**Comment by ItsMadruga** [comment]
> Before:
> 
> ```
> [ 2024-04-12T04:07:12.678    10190: 14840: 14840 I/LSPosed-Bridge  ] [Chats Filter] Tabs: [200, 800, 300, 600, 400]
> .... Back button press ....
> [ 2024-04-12T04:07:19.293    10190: 14840: 14840 I/LSPosed-Bridge  ] [Chats Filter] Tabs: [200, 300, 600, 800]
> ```
> 
> After:
> 
> ```
> [ 2024-04-12T04:09:56.565    10190: 16585: 16585 I/LSPosed-Bridge  ] [Chats Filter] Tabs: [200, 800, 300, 600, 400]
> .... Back button press ....
> [ 2024-04-12T04:09:59.754    10190: 16585: 16585 I/LSPosed-Bridge  ] [Chats Filter] Tabs: [200, 800, 300, 600, 400]
> ```

I understand, I thought I was talking about the chat list, but it's about the tab list

**Comment by BryanGIG** [comment]
Ahh, sorry for the confusion. I mentioned the tab list issue not the chat list.

I haven't been able to reproduce the chat list issue. Just the tab list issue for now.

**Comment by RevealedSoulEven** [comment]
@BryanGIG pro here.
I used your kmrite source back in 2020-21 to make my kotlin injector. Feeling good to see you again🥹♥️

**Pull request closed without merging**
