### PR TITLE
`dev4mod latest commit and i optimized all plugins, fix all bugs, delete igstatues, new hidetabs code, fix-filterChats and other stuffs... add support 2.24.8.85 latest play store, versions please test and after merge`

### PR DESCRIPTION
**Pull request by cvnertnc**
`dev4mod latest commit and i optimized all plugins, fix all bugs, delete igstatues, new hidetabs code, fix-filterChats and other stuffs... please test and after merged`

`add support 2.24.8.85 latest play store versions`

### CODE REVIEW

**Comment by HikaruIchijyo** [comment]
Y deleting igstatus?

**Comment by cvnertnc** [comment]
> Y deleting igstatus?

Yes I deleted. It was a slightly problematic module, I will add it after trying it myself. I'll try to add it today.

**Comment by HikaruIchijyo** [comment]
> > Y deleting igstatus?
> 
> Yes I deleted. It was a slightly problematic module, I will add it after trying it myself. I'll try to add it today.

Okies add improvements to it too if u can

**Comment by cvnertnc** [comment]
> > > Y deleting igstatus?
> > 
> > 
> > Yes I deleted. It was a slightly problematic module, I will add it after trying it myself. I'll try to add it today.
> 
> Okies add improvements to it too if u can Like swiping animations etc

Unfortunately I couldn't add it, my code didn't support it.

**Comment by HikaruIchijyo** [comment]
> > > > Y deleting igstatus?
> > > 
> > > 
> > > Yes I deleted. It was a slightly problematic module, I will add it after trying it myself. I'll try to add it today.
> > 
> > Okies add improvements to it too if u can Like swiping animations etc
> 
> Unfortunately I couldn't add it, my code didn't support it.

Rip

**Comment by HikaruIchijyo** [comment]
> > > > > > Y deleting igstatus?
> > > > > 
> > > > > 
> > > > > Yes I deleted. It was a slightly problematic module, I will add it after trying it myself. I'll try to add it today.
> > > > 
> > > > 
> > > > Okies add improvements to it too if u can Like swiping animations etc
> > > 
> > > 
> > > Unfortunately I couldn't add it, my code didn't support it.
> > 
> > Rip
> 
> To me, that igstatus was like a broken feature, I deliberately didn't want it in mine. He said let's try adding it and exploded.😅 I pulled it to see if ItsMadruga would add my fork. this is right now My fork application works very stably.😉 If you want dev4mod latest commit, I created a separate branch for it in my own fork and pulled it too. If you want to try its debug app, here is the [link](https://github.com/ItsMadruga/MdgWa/actions/runs/8880014971)

No issues 
For features request chk #3 better go fr status features first😅 if u can . Dev is busy so as soon as he is free he will test & merge

**Comment by cvnertnc** [comment]
> > > > > > > Y deleting igstatus?
> > > > > > 
> > > > > > 
> > > > > > Yes I deleted. It was a slightly problematic module, I will add it after trying it myself. I'll try to add it today.
> > > > > 
> > > > > 
> > > > > Okies add improvements to it too if u can Like swiping animations etc
> > > > 
> > > > 
> > > > Unfortunately I couldn't add it, my code didn't support it.
> > > 
> > > 
> > > Rip
> > 
> > 
> > To me, that igstatus was like a broken feature, I deliberately didn't want it in mine. He said let's try adding it and exploded.😅 I pulled it to see if ItsMadruga would add my fork. this is right now My fork application works very stably.😉 If you want dev4mod latest commit, I created a separate branch for it in my own fork and pulled it too. If you want to try its debug app, here is the [link](https://github.com/ItsMadruga/MdgWa/actions/runs/8880014971)
> 
> No issues For features request chk #3 better go fr status features first😅 if u can . Dev is busy so as soon as he is free he will test & merge

Ok. If I make an update I'll let you know. Now I have added play store latest version support for Whatsapp. 2.24.8.85

**Pull request closed without merging**
